FROM  mcr.microsoft.com/dotnet/sdk:8.0 as build
WORKDIR /app

COPY ./src ./src
COPY ./CapitalGain.sln ./

RUN dotnet restore
RUN dotnet publish - c Release -o /publish

FROM mcr.microsoft.com/dotnet/runtime:8.0
WORKDIR /app
COPY --from=build /publish .
ENTRYPOINT ["./CapitalGain.CLI"]